tests added
maxcraft/StackCalculator pull request #2
Opened 2018-09-10 23:44 UTC by marykravets

2018-09-11 21:04 UTC, maxcraft requested changes

2018-09-11 21:04 UTC, maxcraft commented on app/src/androidTest/java/com/maxcraft/stackcalculator/MainActivityTest.java
> +                allOf(withId(R.id.btn_push), withText("push"),
Are you sure each field will always have the text you expect? It might be changed with translations.

2018-09-11 22:05 UTC, marykravets reviewed
done

2018-09-11 22:18 UTC, maxcraft requested changes

2018-09-11 22:18 UTC, maxcraft commented on app/src/androidTest/java/com/maxcraft/stackcalculator/MainActivityTest.java
> +        onView(withId(R.id.indicator_txt)).check(matches(withText("-1.5")));
Please check if "-1.5" will always be the same. Some locales might produce ',' instead of '.'.

2018-09-11 23:43 UTC, marykravets reviewed
done

2018-09-12 19:09 UTC, maxcraft approved these changes

2018-09-12 19:09 UTC, merged